### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by JohnB17** [GeyserMC/GeyserConnect#21]
Can someone help me? I am getting this error with the geyser connect pterodactyl egg.
```
java -Xms128M -Xmx2048M -jar GeyserConnect.jar
Exception in thread "main" java.lang.NullPointerException
        at org.geysermc.connect.MasterServer.<init>(MasterServer.java:106)
        at org.geysermc.connect.GeyserConnect.main(GeyserConnect.java:31)
```

**Comment by rtm516** [comment]
Moved as this is a GeyserConnect issue, but it looks like your config is corrupt. I would suggest downloading [this](https://github.com/GeyserMC/GeyserConnect/blob/master/src/main/resources/config.yml) one as pterodactyl sometimes won't generate it properly.
