### ISSUE TITLE
Doesnt work at all.

### ISSUE THREAD

**Issue by satyrnhub** [GeyserMC/GeyserConnect#3]
Latest build (#4), this error message: `[14:36:03 ERROR] An exception occurred in RakNet
java.lang.RuntimeException: Unable to inflate buffer data
	at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:83) ~[GeyserConnect.jar:?]
	at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:19) ~[GeyserConnect.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:271) ~[GeyserConnect.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:28) ~[GeyserConnect.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[GeyserConnect.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[GeyserConnect.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[GeyserConnect.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:400) ~[GeyserConnect.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[GeyserConnect.jar:?]
	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[GeyserConnect.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [GeyserConnect.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [GeyserConnect.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [GeyserConnect.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [GeyserConnect.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [GeyserConnect.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [GeyserConnect.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [GeyserConnect.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel.read(EpollDatagramChannel.java:688) [GeyserConnect.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:57) [GeyserConnect.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:507) [GeyserConnect.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502) [GeyserConnect.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) [GeyserConnect.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [GeyserConnect.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [GeyserConnect.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.util.zip.DataFormatException: No zlib header
	at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:32) ~[GeyserConnect.jar:?]
	at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:64) ~[GeyserConnect.jar:?]
	... 24 more`

**Comment by rtm516** [comment]
Geyser doesn't support 1.16 yet and because of this neither does GeyserConnect. I will update this to add 1.16 support when Geyser supports it.
