### ISSUE TITLE
srv resolving doesn't work

### ISSUE THREAD

**Issue by creeper123123321** [GeyserMC/GeyserConnect#35]
on geyserconnect.net, the ips without SRV records works fine, but the srv resolver is having some issues, maybe it is related with this netty dns resolver issue: https://github.com/VelocityPowered/Velocity/issues/297#issuecomment-619482032
(the PacketLib uses netty resolver)

**Comment by rtm516** [comment]
I believe this is due to how 1.17 handles srv resolving in java edition, I'm waiting on Mojang to fix it or at least close the issue on their bug tracker before investigating.

**Comment by creeper123123321** [comment]
```
[PacketLib] Attempting SRV lookup for "_minecraft._tcp.hypixel.net".
[PacketLib] Failed to resolve SRV record.
java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.epoll.EpollEventLoop
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:461)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:87)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:81)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:323)
	at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:227)
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:456)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:476)
	at com.github.steveice10.packetlib.tcp.TcpClientSession.resolveAddress(TcpClientSession.java:169)
	at com.github.steveice10.packetlib.tcp.TcpClientSession.lambda$connect$0(TcpClientSession.java:127)
	at com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:146)
	at com.github.steveice10.packetlib.tcp.TcpSession.connect(TcpSession.java:63)
	at org.geysermc.connector.network.session.GeyserSession.connectDownstream(GeyserSession.java:819)
	at org.geysermc.connector.network.session.GeyserSession.lambda$authenticate$2(GeyserSession.java:587)
	at java.base/java.lang.Thread.run(Thread.java:831)
[PacketLib] Resolved hypixel.net -> 104.17.71.15
[09:09:11 INFO] creeper12312332 se desconectou do servidor Java remoto no endereço hypixel.net por causa de Connection timed out.
io.netty.channel.ConnectTimeoutException: connection timed out: hypixel.net/104.17.71.15:25565
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:576)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by creeper123123321** [comment]
should be fixed by https://github.com/GeyserMC/PacketLib/pull/1

**Comment by creeper123123321** [comment]
https://github.com/GeyserMC/PacketLib/commit/7e807b10805f5db78e9f9956e7a80fd85b6b81de related commit
